#!/bin/bash 

git clone https://github.com/smcameron/space-nerds-in-space.git
cd space-nerds-in-space
make 

cp -R * ~/snis-live/airootfs/etc/skel/
cd ..
chmod +x airootfs/root/customize_airootfs.sh
sh ./build.sh -v

