# Make sure to run the container with --privileged
# Needs a volume mounted to /snis-live/out/
#
# command example:
#   docker run --privileged -v $HOME/snislive-docker/:/snis-live/out/ snis-live
#

FROM base/archlinux

RUN pacman -Sy --noconfirm \
    git \
    archiso \
    base-devel

COPY ./airootfs /snis-live
COPY ./efiboot /snis-live
COPY ./syslinux /snis-live
COPY ./autobuild /snis-live
COPY ./build.sh /snis-live
COPY ./mkinitcpio.conf /snis-live
COPY ./packages.x86_64 /snis-live
COPY ./pacman.conf /snis-live

CMD cd snis-live && sh ./autobuild
